### ISSUE TITLE
New paper recommend

### ISSUE THREAD

**Issue by hackerchenzhuo** [AspirinCode/papers-for-molecular-design-using-DL#1]
Hi, we have two new related paper recommendations, do you think it fits the theme of this project?  😄
- [Mol-Instructions: A Large-Scale Biomolecular Instruction Dataset for Large Language Models](https://arxiv.org/abs/2306.08018) [[project](https://github.com/zjunlp/Mol-Instructions)]
- [Domain-Agnostic Molecular Generation with Self-feedback](https://arxiv.org/pdf/2301.11259.pdf) [[project](https://github.com/zjunlp/MolGen)]

**Comment by AspirinCode** [comment]
Thank you for the recommendation, I have updated it.
