### ISSUE TITLE
new paper

### ISSUE THREAD

**Issue by feiyang-cai** [AspirinCode/papers-for-molecular-design-using-DL#11]
Thanks for the wonderful list. 

We recently had a paper named "A Foundation Model for Chemical Design and Property Prediction". I am not sure if this is suitable for this list. 

Here are the links to the paper and codes.

Paper: https://arxiv.org/abs/2410.21422
Codes: https://github.com/TheLuoFengLab/ChemFM.

Thanks,
Feiyang

**Comment by AspirinCode** [comment]
I've updated.

**Comment by AspirinCode** [comment]
I've updated.

**Comment by AspirinCode** [comment]
I've updated.

**Comment by feiyang-cai** [comment]
@AspirinCode Thank you!
