### ISSUE TITLE
Paper recommendation

### ISSUE THREAD

**Issue by GRAPH-0** [AspirinCode/papers-for-molecular-design-using-DL#3]
Hi @AspirinCode ,

Thanks for your wonderful paper list!
Would you mind to consider our papers on molecule generation as follows:
1. Title: Conditional Diffusion Based on Discrete Graph Structures for Molecular Graph Generation
    Paper: https://arxiv.org/abs/2301.00427
    Code: https://github.com/GRAPH-0/CDGS
2. Title: Learning Joint 2D & 3D Diffusion Models for Complete Molecule Generation 
    Paper: https://arxiv.org/abs/2305.12347
    Code: https://github.com/GRAPH-0/JODO

**Comment by AspirinCode** [comment]
Thanks for the recommendation, already updated.
