### ISSUE TITLE
Suggestion to Include Papers on an emerging subfield - Material Design

### ISSUE THREAD

**Issue by ZohebAbai** [AspirinCode/papers-for-molecular-design-using-DL#8]
Hello @AspirinCode 

Thank you so much for actively maintaining this repository. I truly appreciate the effort and dedication you’ve put into it!

The repository features papers related to molecular generation in general and in particular on drug design, which is understandable. I believe there is a growing and exciting subfield that could be beneficial to include: `material design`. As this area continues to expand, I think it would be valuable to have resources related to material design within this repository, especially since I haven’t found any other repositories that cover this emerging field.

To contribute to this effort, I would like to suggest adding two recent and significant papers on material design:

Paper: [Scaling deep learning for materials discovery](https://www.nature.com/articles/s41586-023-06735-9)
GitHub Repository: [Google-Deepmind Materials Discovery](https://github.com/google-deepmind/materials_discovery)

Paper: [MatterGen: a generative model for inorganic materials design](https://arxiv.org/abs/2312.03687)
Unfortunately, there is no official GitHub repository available for this paper at the moment.

I believe these papers would be a valuable addition to the repository and would help broaden its scope to include material design. I’m also happy to assist in any way I can to help this community grow.

Best regards,

**Comment by ZohebAbai** [comment]
If you agree, let me know. I will raise a PR.

**Comment by AspirinCode** [comment]
I couldn't agree more.

**Comment by AspirinCode** [comment]
> Hello @AspirinCode
> 
> Thank you so much for actively maintaining this repository. I truly appreciate the effort and dedication you’ve put into it!
> 
> The repository features papers related to molecular generation in general and in particular on drug design, which is understandable. I believe there is a growing and exciting subfield that could be beneficial to include: `material design`. As this area continues to expand, I think it would be valuable to have resources related to material design within this repository, especially since I haven’t found any other repositories that cover this emerging field.
> 
> To contribute to this effort, I would like to suggest adding two recent and significant papers on material design:
> 
> Paper: [Scaling deep learning for materials discovery](https://www.nature.com/articles/s41586-023-06735-9) GitHub Repository: [Google-Deepmind Materials Discovery](https://github.com/google-deepmind/materials_discovery)
> 
> Paper: [MatterGen: a generative model for inorganic materials design](https://arxiv.org/abs/2312.03687) Unfortunately, there is no official GitHub repository available for this paper at the moment.
> 
> I believe these papers would be a valuable addition to the repository and would help broaden its scope to include material design. I’m also happy to assist in any way I can to help this community grow.
> 
> Best regards,

I couldn't agree more.
