### ISSUE TITLE
Revelant works on molecule editing

### ISSUE THREAD

**Issue by chao1224** [AspirinCode/papers-for-molecular-design-using-DL#9]
Hi @AspirinCode , very impressive list!

We have a series of works that are also related to molecule editing or lead optimization
- [GraphCG](https://openreview.net/forum?id=wyU3Q4gahM), unsupervised molecule editing
- [MoleculeSTM](https://www.nature.com/articles/s42256-023-00759-6), zero-shot text-guided molecule editing
- [ChatDrug](https://openreview.net/forum?id=yRrPfKyJQ2), LLM-guided molecule editing

**Comment by AspirinCode** [comment]
> Hi @AspirinCode , very impressive list!
> 
> We have a series of works that are also related to molecule editing or lead optimization
> 
> * [GraphCG](https://openreview.net/forum?id=wyU3Q4gahM), unsupervised molecule editing
> * [MoleculeSTM](https://www.nature.com/articles/s42256-023-00759-6), zero-shot text-guided molecule editing
> * [ChatDrug](https://openreview.net/forum?id=yRrPfKyJQ2), LLM-guided molecule editing

Updates have been added.

**Comment by AspirinCode** [comment]
> Hi @AspirinCode , very impressive list!
> 
> We have a series of works that are also related to molecule editing or lead optimization
> 
> * [GraphCG](https://openreview.net/forum?id=wyU3Q4gahM), unsupervised molecule editing
> * [MoleculeSTM](https://www.nature.com/articles/s42256-023-00759-6), zero-shot text-guided molecule editing
> * [ChatDrug](https://openreview.net/forum?id=yRrPfKyJQ2), LLM-guided molecule editing
